# Generated by Django 4.2.4 on 2023-10-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_collegeevent_id_alter_contact_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weddingevent",
            name="cuisine",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="weddingevent",
            name="package",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
    ]
