# Generated by Django 4.2.4 on 2023-11-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_weddingevent_cuisine_weddingevent_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="collegeevent",
            name="cuisine",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="collegeevent",
            name="package",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="partiesevent",
            name="cuisine",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="partiesevent",
            name="package",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="technicalevent",
            name="cuisine",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="technicalevent",
            name="package",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
    ]
