# Generated by Django 4.2.4 on 2023-11-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_collegeevent_cuisine_collegeevent_package_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventadvisor",
            name="cuisine",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="eventadvisor",
            name="package",
            field=models.CharField(
                choices=[("IND", "Indian"), ("CHN", "Chinese"), ("ARB", "Arabian")],
                default="option1",
                max_length=10,
            ),
        ),
    ]
